### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by ArtemRuslanovich** [probably-kit/todo-list#1]
After I've done the task, I want the screams of the PAPICH to be heard. Is it possible to do this? For example : "NYYYYYAAAAAA AHAHAHAHHAHAHAH" 
![image](https://github.com/probably-kit/todo-list/assets/94451303/f3ea123b-b9b9-4900-a205-4aae0bafbbf3)

**Comment by probably-kit** [comment]
i can but i don't wanna

**Comment by probably-kit** [comment]
i can but i don't wanna
